name: Galvanize Full Stack: one student's journey
description: learning to code at Galvanize's full stack program and writing about it
meta_description: "Documenting my experience learning to code at Galvanize's full stack program"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jonharlem.github.io/'
google_analytics: 'UA-69353602-1'

# Details for the RSS feed generator
url:            'blog url'
author:         'Jon Harlem'
